const spotifySampleRes = {
    seeds: [
        {
            afterFilteringSize: 313,
            afterRelinkingSize: 313,
            href: 'https://api.spotify.com/v1/artists/4NHQUGzhtTLFvgF5SZesLK',
            id: '4NHQUGzhtTLFvgF5SZesLK',
            initialPoolSize: 500,
            type: 'ARTIST',
        },
        {
            afterFilteringSize: 313,
            afterRelinkingSize: 313,
            href: 'https://api.spotify.com/v1/tracks/0c6xIDDpzE81m2q797ordA',
            id: '0c6xIDDpzE81m2q797ordA',
            initialPoolSize: 500,
            type: 'TRACK',
        },
        {
            afterFilteringSize: 313,
            afterRelinkingSize: 313,
            href: null,
            id: 'classical',
            initialPoolSize: 517,
            type: 'GENRE',
        },
        {
            afterFilteringSize: 313,
            afterRelinkingSize: 313,
            href: null,
            id: 'country',
            initialPoolSize: 999,
            type: 'GENRE',
        },
    ],
    tracks: [
        {
            album: {
                album_type: 'ALBUM',
                total_tracks: 11,
                available_markets: [
                    'AR',
                    'AU',
                    'AT',
                    'BE',
                    'BO',
                    'BR',
                    'BG',
                    'CA',
                    'CL',
                    'CO',
                    'CR',
                    'CY',
                    'CZ',
                    'DK',
                    'DO',
                    'DE',
                    'EC',
                    'EE',
                    'SV',
                    'FI',
                    'FR',
                    'GR',
                    'GT',
                    'HN',
                    'HK',
                    'HU',
                    'IS',
                    'IE',
                    'IT',
                    'LV',
                    'LT',
                    'LU',
                    'MY',
                    'MT',
                    'MX',
                    'NL',
                    'NZ',
                    'NI',
                    'NO',
                    'PA',
                    'PY',
                    'PE',
                    'PH',
                    'PL',
                    'PT',
                    'SG',
                    'SK',
                    'ES',
                    'SE',
                    'CH',
                    'TW',
                    'TR',
                    'UY',
                    'US',
                    'GB',
                    'AD',
                    'LI',
                    'MC',
                    'ID',
                    'JP',
                    'TH',
                    'VN',
                    'RO',
                    'IL',
                    'ZA',
                    'SA',
                    'AE',
                    'BH',
                    'QA',
                    'OM',
                    'KW',
                    'EG',
                    'MA',
                    'DZ',
                    'TN',
                    'LB',
                    'JO',
                    'PS',
                    'IN',
                    'BY',
                    'KZ',
                    'MD',
                    'UA',
                    'AL',
                    'BA',
                    'HR',
                    'ME',
                    'MK',
                    'RS',
                    'SI',
                    'KR',
                    'BD',
                    'PK',
                    'LK',
                    'GH',
                    'KE',
                    'NG',
                    'TZ',
                    'UG',
                    'AG',
                    'AM',
                    'BS',
                    'BB',
                    'BZ',
                    'BT',
                    'BW',
                    'BF',
                    'CV',
                    'CW',
                    'DM',
                    'FJ',
                    'GM',
                    'GE',
                    'GD',
                    'GW',
                    'GY',
                    'HT',
                    'JM',
                    'KI',
                    'LS',
                    'LR',
                    'MW',
                    'MV',
                    'ML',
                    'MH',
                    'FM',
                    'NA',
                    'NR',
                    'NE',
                    'PW',
                    'PG',
                    'WS',
                    'SM',
                    'ST',
                    'SN',
                    'SC',
                    'SL',
                    'SB',
                    'KN',
                    'LC',
                    'VC',
                    'SR',
                    'TL',
                    'TO',
                    'TT',
                    'TV',
                    'VU',
                    'AZ',
                    'BN',
                    'BI',
                    'KH',
                    'CM',
                    'TD',
                    'KM',
                    'GQ',
                    'SZ',
                    'GA',
                    'GN',
                    'KG',
                    'LA',
                    'MO',
                    'MR',
                    'MN',
                    'NP',
                    'RW',
                    'TG',
                    'UZ',
                    'ZW',
                    'BJ',
                    'MG',
                    'MU',
                    'MZ',
                    'AO',
                    'CI',
                    'DJ',
                    'ZM',
                    'CD',
                    'CG',
                    'IQ',
                    'LY',
                    'TJ',
                    'VE',
                    'ET',
                    'XK',
                ],
                external_urls: {
                    spotify:
                        'https://open.spotify.com/album/56XXDc04Gugu3CknMcsWLY',
                },
                href: 'https://api.spotify.com/v1/albums/56XXDc04Gugu3CknMcsWLY',
                id: '56XXDc04Gugu3CknMcsWLY',
                images: [
                    {
                        url: 'https://i.scdn.co/image/ab67616d0000b27333452cbadb9db9189edd7250',
                        height: 640,
                        width: 640,
                    },
                    {
                        url: 'https://i.scdn.co/image/ab67616d00001e0233452cbadb9db9189edd7250',
                        height: 300,
                        width: 300,
                    },
                    {
                        url: 'https://i.scdn.co/image/ab67616d0000485133452cbadb9db9189edd7250',
                        height: 64,
                        width: 64,
                    },
                ],
                name: 'Bigger',
                release_date: '2018-06-08',
                release_date_precision: 'day',
                type: 'album',
                uri: 'spotify:album:56XXDc04Gugu3CknMcsWLY',
                artists: [
                    {
                        external_urls: {
                            spotify:
                                'https://open.spotify.com/artist/0hYxQe3AK5jBPCr5MumLHD',
                        },
                        href: 'https://api.spotify.com/v1/artists/0hYxQe3AK5jBPCr5MumLHD',
                        id: '0hYxQe3AK5jBPCr5MumLHD',
                        name: 'Sugarland',
                        type: 'artist',
                        uri: 'spotify:artist:0hYxQe3AK5jBPCr5MumLHD',
                    },
                ],
            },
            artists: [
                {
                    external_urls: {
                        spotify:
                            'https://open.spotify.com/artist/0hYxQe3AK5jBPCr5MumLHD',
                    },
                    href: 'https://api.spotify.com/v1/artists/0hYxQe3AK5jBPCr5MumLHD',
                    id: '0hYxQe3AK5jBPCr5MumLHD',
                    name: 'Sugarland',
                    type: 'artist',
                    uri: 'spotify:artist:0hYxQe3AK5jBPCr5MumLHD',
                },
                {
                    external_urls: {
                        spotify:
                            'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02',
                    },
                    href: 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02',
                    id: '06HL4z0CvFAxyc27GXpf02',
                    name: 'テイラー・スウィフト',
                    type: 'artist',
                    uri: 'spotify:artist:06HL4z0CvFAxyc27GXpf02',
                },
            ],
            available_markets: [
                'AR',
                'AU',
                'AT',
                'BE',
                'BO',
                'BR',
                'BG',
                'CA',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DK',
                'DO',
                'DE',
                'EC',
                'EE',
                'SV',
                'FI',
                'FR',
                'GR',
                'GT',
                'HN',
                'HK',
                'HU',
                'IS',
                'IE',
                'IT',
                'LV',
                'LT',
                'LU',
                'MY',
                'MT',
                'MX',
                'NL',
                'NZ',
                'NI',
                'NO',
                'PA',
                'PY',
                'PE',
                'PH',
                'PL',
                'PT',
                'SG',
                'SK',
                'ES',
                'SE',
                'CH',
                'TW',
                'TR',
                'UY',
                'US',
                'GB',
                'AD',
                'LI',
                'MC',
                'ID',
                'JP',
                'TH',
                'VN',
                'RO',
                'IL',
                'ZA',
                'SA',
                'AE',
                'BH',
                'QA',
                'OM',
                'KW',
                'EG',
                'MA',
                'DZ',
                'TN',
                'LB',
                'JO',
                'PS',
                'IN',
                'BY',
                'KZ',
                'MD',
                'UA',
                'AL',
                'BA',
                'HR',
                'ME',
                'MK',
                'RS',
                'SI',
                'KR',
                'BD',
                'PK',
                'LK',
                'GH',
                'KE',
                'NG',
                'TZ',
                'UG',
                'AG',
                'AM',
                'BS',
                'BB',
                'BZ',
                'BT',
                'BW',
                'BF',
                'CV',
                'CW',
                'DM',
                'FJ',
                'GM',
                'GE',
                'GD',
                'GW',
                'GY',
                'HT',
                'JM',
                'KI',
                'LS',
                'LR',
                'MW',
                'MV',
                'ML',
                'MH',
                'FM',
                'NA',
                'NR',
                'NE',
                'PW',
                'PG',
                'WS',
                'SM',
                'ST',
                'SN',
                'SC',
                'SL',
                'SB',
                'KN',
                'LC',
                'VC',
                'SR',
                'TL',
                'TO',
                'TT',
                'TV',
                'VU',
                'AZ',
                'BN',
                'BI',
                'KH',
                'CM',
                'TD',
                'KM',
                'GQ',
                'SZ',
                'GA',
                'GN',
                'KG',
                'LA',
                'MO',
                'MR',
                'MN',
                'NP',
                'RW',
                'TG',
                'UZ',
                'ZW',
                'BJ',
                'MG',
                'MU',
                'MZ',
                'AO',
                'CI',
                'DJ',
                'ZM',
                'CD',
                'CG',
                'IQ',
                'LY',
                'TJ',
                'VE',
                'ET',
                'XK',
            ],
            disc_number: 1,
            duration_ms: 215106,
            explicit: false,
            external_ids: {
                isrc: 'USUM71804122',
            },
            external_urls: {
                spotify:
                    'https://open.spotify.com/track/7fRruZ12gXGwBs0zXQ6e5V',
            },
            href: 'https://api.spotify.com/v1/tracks/7fRruZ12gXGwBs0zXQ6e5V',
            id: '7fRruZ12gXGwBs0zXQ6e5V',
            name: 'Babe',
            popularity: 58,
            preview_url: null,
            track_number: 7,
            type: 'track',
            uri: 'spotify:track:7fRruZ12gXGwBs0zXQ6e5V',
            is_local: false,
        },
    ],
};

export default spotifySampleRes;
